services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    volumes:
      - ./overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
      - TZ=${TIMEZONE}
      - LOG_LEVEL=${LOG_LEVEL}
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ./sonarr:/config
      - ${MEDIA_DIR}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
      - TZ=${TIMEZONE}
      - LOG_LEVEL=${LOG_LEVEL}
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ./radarr:/config
      - ${MEDIA_DIR}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
      - TZ=${TIMEZONE}
      - LOG_LEVEL=${LOG_LEVEL}
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    environment:
      - PGID=${GROUP_ID}
      - PUID=${USER_ID}
      - TZ=${TIMEZONE}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - flaresolverr
  recyclarr:
    image: recyclarr/recyclarr
    container_name: recyclarr
    volumes:
      - ./recyclarr:/config
    user: ${USER_ID}:${GROUP_ID}
    restart: unless-stopped
    read_only: true
    tmpfs: /tmp
    environment:
      - TZ=${TIMEZONE}
      - RECYCLARR_CREATE_CONFIG=true
      - SONARR_API_KEY=${SONARR_API_KEY}
      - RADARR_API_KEY=${RADARR_API_KEY}
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    ports:
      - 8191:8191
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TIMEZONE}
